#ifndef DATATYPES_H_
#define DATATYPES_H_

#include <stdint.h>
#include <stdbool.h>

typedef CAN_PACKET_ID;


typedef enum {
	HW_TYPE_VESC = 0,
	HW_TYPE_VESC_BMS = 1,
	HW_TYPE_CUSTOM_MODULE = 2
} HW_TYPE;

typedef enum {
	COMM_FW_VERSION					= 0,
	COMM_GET_VALUES					= 4,
	COMM_SET_DUTY					= 5,
	COMM_SET_CURRENT				= 6,
	COMM_SET_CURRENT_BRAKE			= 7,
	COMM_SET_RPM					= 8,
	COMM_SET_POS					= 9,
	COMM_GET_MCCONF					= 14,
	COMM_GET_APPCONF				= 17,
	COMM_REBOOT						= 29,
	COMM_ALIVE						= 30,
	COMM_FORWARD_CAN				= 34,
	COMM_PING_CAN					= 62,
	COMM_GET_VALUES_SELECTIVE		= 50,
	COMM_SHUTDOWN					= 156,
} COMM_PACKET_ID;

typedef enum {
	CAN_PACKET_SET_DUTY						= 0,
	CAN_PACKET_SET_CURRENT					= 1,
	CAN_PACKET_SET_CURRENT_BRAKE			= 2,
	CAN_PACKET_SET_RPM						= 3,
	CAN_PACKET_SET_POS						= 4,
	CAN_PACKET_FILL_RX_BUFFER				= 5,
	CAN_PACKET_FILL_RX_BUFFER_LONG			= 6,
	CAN_PACKET_PROCESS_RX_BUFFER			= 7,
	CAN_PACKET_PROCESS_SHORT_BUFFER			= 8,
	CAN_PACKET_STATUS						= 9,
	CAN_PACKET_SET_CURRENT_REL				= 10,
	CAN_PACKET_SET_CURRENT_BRAKE_REL		= 11,
	CAN_PACKET_SET_CURRENT_HANDBRAKE		= 12,
	CAN_PACKET_SET_CURRENT_HANDBRAKE_REL	= 13,
	CAN_PACKET_STATUS_2						= 14,
	CAN_PACKET_STATUS_3						= 15,
	CAN_PACKET_STATUS_4						= 16,
	CAN_PACKET_PING							= 17,
	CAN_PACKET_PONG							= 18,
	CAN_PACKET_STATUS_5						= 27,
	CAN_PACKET_SHUTDOWN						= 31,
	CAN_PACKET_STATUS_6						= 58,
	CAN_PACKET_MAKE_ENUM_32_BITS			= 0xFFFFFFFF,
} CAN_PACKET_ID;

#endif /* DATATYPES_H_ */